namespace Persistencia.Migrations.Entity
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class CascadeAdd : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Abastecimento", "VeiculoId", "dbo.Veiculo");
            DropForeignKey("dbo.Multa", "MotoristaId", "dbo.Motorista");
            DropForeignKey("dbo.Sinistro", "MotoristaId", "dbo.Motorista");
            DropForeignKey("dbo.Viagem", "MotoristaId", "dbo.Motorista");
            DropForeignKey("dbo.Aluguel", "ClienteId", "dbo.Cliente");
            DropForeignKey("dbo.Solicitacao", "ClienteId", "dbo.Cliente");
            DropForeignKey("dbo.Aluguel", "VeiculoId", "dbo.Veiculo");
            DropForeignKey("dbo.Manutencao", "VeiculoId", "dbo.Veiculo");
            DropForeignKey("dbo.Multa", "VeiculoId", "dbo.Veiculo");
            DropForeignKey("dbo.Sinistro", "VeiculoId", "dbo.Veiculo");
            DropForeignKey("dbo.PecasManutencao", "ManutencaoId", "dbo.Manutencao");
            DropForeignKey("dbo.PecasManutencao", "PecaId", "dbo.Peca");
            DropForeignKey("dbo.Peca", "FornecedorId", "dbo.Fornecedor");
            DropForeignKey("dbo.Viagem", "VeiculoId", "dbo.Veiculo");
            DropIndex("dbo.Abastecimento", new[] { "VeiculoId" });
            DropIndex("dbo.Aluguel", new[] { "VeiculoId" });
            DropIndex("dbo.Aluguel", new[] { "ClienteId" });
            DropIndex("dbo.Manutencao", new[] { "VeiculoId" });
            DropIndex("dbo.PecasManutencao", new[] { "PecaId" });
            DropIndex("dbo.PecasManutencao", new[] { "ManutencaoId" });
            DropIndex("dbo.Peca", new[] { "FornecedorId" });
            DropIndex("dbo.Multa", new[] { "VeiculoId" });
            DropIndex("dbo.Multa", new[] { "MotoristaId" });
            DropIndex("dbo.Sinistro", new[] { "VeiculoId" });
            DropIndex("dbo.Sinistro", new[] { "MotoristaId" });
            DropIndex("dbo.Solicitacao", new[] { "ClienteId" });
            DropIndex("dbo.Viagem", new[] { "VeiculoId" });
            DropIndex("dbo.Viagem", new[] { "MotoristaId" });
            DropPrimaryKey("dbo.Veiculo");
            AddColumn("dbo.Abastecimento", "Veiculo_VeiculoId", c => c.Long());
            AddColumn("dbo.Abastecimento", "Veiculo_Placa", c => c.String(maxLength: 128));
            AddColumn("dbo.Abastecimento", "Veiculo_CodRenavam", c => c.String(maxLength: 128));
            AddColumn("dbo.Aluguel", "Veiculo_VeiculoId", c => c.Long());
            AddColumn("dbo.Aluguel", "Veiculo_Placa", c => c.String(maxLength: 128));
            AddColumn("dbo.Aluguel", "Veiculo_CodRenavam", c => c.String(maxLength: 128));
            AddColumn("dbo.Manutencao", "Veiculo_VeiculoId", c => c.Long());
            AddColumn("dbo.Manutencao", "Veiculo_Placa", c => c.String(maxLength: 128));
            AddColumn("dbo.Manutencao", "Veiculo_CodRenavam", c => c.String(maxLength: 128));
            AddColumn("dbo.Multa", "Veiculo_VeiculoId", c => c.Long());
            AddColumn("dbo.Multa", "Veiculo_Placa", c => c.String(maxLength: 128));
            AddColumn("dbo.Multa", "Veiculo_CodRenavam", c => c.String(maxLength: 128));
            AddColumn("dbo.Sinistro", "Veiculo_VeiculoId", c => c.Long());
            AddColumn("dbo.Sinistro", "Veiculo_Placa", c => c.String(maxLength: 128));
            AddColumn("dbo.Sinistro", "Veiculo_CodRenavam", c => c.String(maxLength: 128));
            AddColumn("dbo.Viagem", "Veiculo_VeiculoId", c => c.Long());
            AddColumn("dbo.Viagem", "Veiculo_Placa", c => c.String(maxLength: 128));
            AddColumn("dbo.Viagem", "Veiculo_CodRenavam", c => c.String(maxLength: 128));
            AlterColumn("dbo.Aluguel", "VeiculoId", c => c.Long(nullable: false));
            AlterColumn("dbo.Aluguel", "ClienteId", c => c.Long(nullable: false));
            AlterColumn("dbo.Veiculo", "VeiculoId", c => c.Long(nullable: false));
            AlterColumn("dbo.Veiculo", "Placa", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Veiculo", "CodRenavam", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Manutencao", "VeiculoId", c => c.Long(nullable: false));
            AlterColumn("dbo.PecasManutencao", "PecaId", c => c.Long(nullable: false));
            AlterColumn("dbo.PecasManutencao", "ManutencaoId", c => c.Long(nullable: false));
            AlterColumn("dbo.Peca", "FornecedorId", c => c.Long(nullable: false));
            AlterColumn("dbo.Multa", "VeiculoId", c => c.Long(nullable: false));
            AlterColumn("dbo.Multa", "MotoristaId", c => c.Long(nullable: false));
            AlterColumn("dbo.Sinistro", "VeiculoId", c => c.Long(nullable: false));
            AlterColumn("dbo.Sinistro", "MotoristaId", c => c.Long(nullable: false));
            AlterColumn("dbo.Solicitacao", "ClienteId", c => c.Long(nullable: false));
            AlterColumn("dbo.Viagem", "VeiculoId", c => c.Long(nullable: false));
            AlterColumn("dbo.Viagem", "MotoristaId", c => c.Long(nullable: false));
            AddPrimaryKey("dbo.Veiculo", new[] { "VeiculoId", "Placa", "CodRenavam" });
            CreateIndex("dbo.Abastecimento", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" });
            CreateIndex("dbo.Aluguel", "ClienteId");
            CreateIndex("dbo.Aluguel", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" });
            CreateIndex("dbo.Manutencao", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" });
            CreateIndex("dbo.PecasManutencao", "PecaId");
            CreateIndex("dbo.PecasManutencao", "ManutencaoId");
            CreateIndex("dbo.Peca", "FornecedorId");
            CreateIndex("dbo.Multa", "MotoristaId");
            CreateIndex("dbo.Multa", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" });
            CreateIndex("dbo.Sinistro", "MotoristaId");
            CreateIndex("dbo.Sinistro", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" });
            CreateIndex("dbo.Solicitacao", "ClienteId");
            CreateIndex("dbo.Viagem", "MotoristaId");
            CreateIndex("dbo.Viagem", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" });
            AddForeignKey("dbo.Abastecimento", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" }, "dbo.Veiculo", new[] { "VeiculoId", "Placa", "CodRenavam" });
            AddForeignKey("dbo.Multa", "MotoristaId", "dbo.Motorista", "MotoristaId", cascadeDelete: true);
            AddForeignKey("dbo.Sinistro", "MotoristaId", "dbo.Motorista", "MotoristaId", cascadeDelete: true);
            AddForeignKey("dbo.Viagem", "MotoristaId", "dbo.Motorista", "MotoristaId", cascadeDelete: true);
            AddForeignKey("dbo.Aluguel", "ClienteId", "dbo.Cliente", "ClienteId", cascadeDelete: true);
            AddForeignKey("dbo.Solicitacao", "ClienteId", "dbo.Cliente", "ClienteId", cascadeDelete: true);
            AddForeignKey("dbo.Aluguel", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" }, "dbo.Veiculo", new[] { "VeiculoId", "Placa", "CodRenavam" });
            AddForeignKey("dbo.Manutencao", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" }, "dbo.Veiculo", new[] { "VeiculoId", "Placa", "CodRenavam" });
            AddForeignKey("dbo.Multa", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" }, "dbo.Veiculo", new[] { "VeiculoId", "Placa", "CodRenavam" });
            AddForeignKey("dbo.Sinistro", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" }, "dbo.Veiculo", new[] { "VeiculoId", "Placa", "CodRenavam" });
            AddForeignKey("dbo.PecasManutencao", "ManutencaoId", "dbo.Manutencao", "ManutencaoId", cascadeDelete: true);
            AddForeignKey("dbo.PecasManutencao", "PecaId", "dbo.Peca", "PecaId", cascadeDelete: true);
            AddForeignKey("dbo.Peca", "FornecedorId", "dbo.Fornecedor", "FornecedorId", cascadeDelete: true);
            AddForeignKey("dbo.Viagem", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" }, "dbo.Veiculo", new[] { "VeiculoId", "Placa", "CodRenavam" });
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Viagem", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" }, "dbo.Veiculo");
            DropForeignKey("dbo.Peca", "FornecedorId", "dbo.Fornecedor");
            DropForeignKey("dbo.PecasManutencao", "PecaId", "dbo.Peca");
            DropForeignKey("dbo.PecasManutencao", "ManutencaoId", "dbo.Manutencao");
            DropForeignKey("dbo.Sinistro", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" }, "dbo.Veiculo");
            DropForeignKey("dbo.Multa", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" }, "dbo.Veiculo");
            DropForeignKey("dbo.Manutencao", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" }, "dbo.Veiculo");
            DropForeignKey("dbo.Aluguel", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" }, "dbo.Veiculo");
            DropForeignKey("dbo.Solicitacao", "ClienteId", "dbo.Cliente");
            DropForeignKey("dbo.Aluguel", "ClienteId", "dbo.Cliente");
            DropForeignKey("dbo.Viagem", "MotoristaId", "dbo.Motorista");
            DropForeignKey("dbo.Sinistro", "MotoristaId", "dbo.Motorista");
            DropForeignKey("dbo.Multa", "MotoristaId", "dbo.Motorista");
            DropForeignKey("dbo.Abastecimento", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" }, "dbo.Veiculo");
            DropIndex("dbo.Viagem", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" });
            DropIndex("dbo.Viagem", new[] { "MotoristaId" });
            DropIndex("dbo.Solicitacao", new[] { "ClienteId" });
            DropIndex("dbo.Sinistro", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" });
            DropIndex("dbo.Sinistro", new[] { "MotoristaId" });
            DropIndex("dbo.Multa", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" });
            DropIndex("dbo.Multa", new[] { "MotoristaId" });
            DropIndex("dbo.Peca", new[] { "FornecedorId" });
            DropIndex("dbo.PecasManutencao", new[] { "ManutencaoId" });
            DropIndex("dbo.PecasManutencao", new[] { "PecaId" });
            DropIndex("dbo.Manutencao", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" });
            DropIndex("dbo.Aluguel", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" });
            DropIndex("dbo.Aluguel", new[] { "ClienteId" });
            DropIndex("dbo.Abastecimento", new[] { "Veiculo_VeiculoId", "Veiculo_Placa", "Veiculo_CodRenavam" });
            DropPrimaryKey("dbo.Veiculo");
            AlterColumn("dbo.Viagem", "MotoristaId", c => c.Long());
            AlterColumn("dbo.Viagem", "VeiculoId", c => c.Long());
            AlterColumn("dbo.Solicitacao", "ClienteId", c => c.Long());
            AlterColumn("dbo.Sinistro", "MotoristaId", c => c.Long());
            AlterColumn("dbo.Sinistro", "VeiculoId", c => c.Long());
            AlterColumn("dbo.Multa", "MotoristaId", c => c.Long());
            AlterColumn("dbo.Multa", "VeiculoId", c => c.Long());
            AlterColumn("dbo.Peca", "FornecedorId", c => c.Long());
            AlterColumn("dbo.PecasManutencao", "ManutencaoId", c => c.Long());
            AlterColumn("dbo.PecasManutencao", "PecaId", c => c.Long());
            AlterColumn("dbo.Manutencao", "VeiculoId", c => c.Long());
            AlterColumn("dbo.Veiculo", "CodRenavam", c => c.String());
            AlterColumn("dbo.Veiculo", "Placa", c => c.String());
            AlterColumn("dbo.Veiculo", "VeiculoId", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Aluguel", "ClienteId", c => c.Long());
            AlterColumn("dbo.Aluguel", "VeiculoId", c => c.Long());
            DropColumn("dbo.Viagem", "Veiculo_CodRenavam");
            DropColumn("dbo.Viagem", "Veiculo_Placa");
            DropColumn("dbo.Viagem", "Veiculo_VeiculoId");
            DropColumn("dbo.Sinistro", "Veiculo_CodRenavam");
            DropColumn("dbo.Sinistro", "Veiculo_Placa");
            DropColumn("dbo.Sinistro", "Veiculo_VeiculoId");
            DropColumn("dbo.Multa", "Veiculo_CodRenavam");
            DropColumn("dbo.Multa", "Veiculo_Placa");
            DropColumn("dbo.Multa", "Veiculo_VeiculoId");
            DropColumn("dbo.Manutencao", "Veiculo_CodRenavam");
            DropColumn("dbo.Manutencao", "Veiculo_Placa");
            DropColumn("dbo.Manutencao", "Veiculo_VeiculoId");
            DropColumn("dbo.Aluguel", "Veiculo_CodRenavam");
            DropColumn("dbo.Aluguel", "Veiculo_Placa");
            DropColumn("dbo.Aluguel", "Veiculo_VeiculoId");
            DropColumn("dbo.Abastecimento", "Veiculo_CodRenavam");
            DropColumn("dbo.Abastecimento", "Veiculo_Placa");
            DropColumn("dbo.Abastecimento", "Veiculo_VeiculoId");
            AddPrimaryKey("dbo.Veiculo", "VeiculoId");
            CreateIndex("dbo.Viagem", "MotoristaId");
            CreateIndex("dbo.Viagem", "VeiculoId");
            CreateIndex("dbo.Solicitacao", "ClienteId");
            CreateIndex("dbo.Sinistro", "MotoristaId");
            CreateIndex("dbo.Sinistro", "VeiculoId");
            CreateIndex("dbo.Multa", "MotoristaId");
            CreateIndex("dbo.Multa", "VeiculoId");
            CreateIndex("dbo.Peca", "FornecedorId");
            CreateIndex("dbo.PecasManutencao", "ManutencaoId");
            CreateIndex("dbo.PecasManutencao", "PecaId");
            CreateIndex("dbo.Manutencao", "VeiculoId");
            CreateIndex("dbo.Aluguel", "ClienteId");
            CreateIndex("dbo.Aluguel", "VeiculoId");
            CreateIndex("dbo.Abastecimento", "VeiculoId");
            AddForeignKey("dbo.Viagem", "VeiculoId", "dbo.Veiculo", "VeiculoId");
            AddForeignKey("dbo.Peca", "FornecedorId", "dbo.Fornecedor", "FornecedorId");
            AddForeignKey("dbo.PecasManutencao", "PecaId", "dbo.Peca", "PecaId");
            AddForeignKey("dbo.PecasManutencao", "ManutencaoId", "dbo.Manutencao", "ManutencaoId");
            AddForeignKey("dbo.Sinistro", "VeiculoId", "dbo.Veiculo", "VeiculoId");
            AddForeignKey("dbo.Multa", "VeiculoId", "dbo.Veiculo", "VeiculoId");
            AddForeignKey("dbo.Manutencao", "VeiculoId", "dbo.Veiculo", "VeiculoId");
            AddForeignKey("dbo.Aluguel", "VeiculoId", "dbo.Veiculo", "VeiculoId");
            AddForeignKey("dbo.Solicitacao", "ClienteId", "dbo.Cliente", "ClienteId");
            AddForeignKey("dbo.Aluguel", "ClienteId", "dbo.Cliente", "ClienteId");
            AddForeignKey("dbo.Viagem", "MotoristaId", "dbo.Motorista", "MotoristaId");
            AddForeignKey("dbo.Sinistro", "MotoristaId", "dbo.Motorista", "MotoristaId");
            AddForeignKey("dbo.Multa", "MotoristaId", "dbo.Motorista", "MotoristaId");
            AddForeignKey("dbo.Abastecimento", "VeiculoId", "dbo.Veiculo", "VeiculoId", cascadeDelete: true);
        }
    }
}
