// <auto-generated />
namespace Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NovoTipoEndereco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NovoTipoEndereco));
        
        string IMigrationMetadata.Id
        {
            get { return "201908240143531_Novo-Tipo-Endereco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
