// <auto-generated />
namespace Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FornecedorPecaVirtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FornecedorPecaVirtual));
        
        string IMigrationMetadata.Id
        {
            get { return "201910221357012_Fornecedor-Peca-Virtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
