// <auto-generated />
namespace Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FirstAfterEnabled : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstAfterEnabled));
        
        string IMigrationMetadata.Id
        {
            get { return "201908162152231_First-After-Enabled"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
