// <auto-generated />
namespace Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewForeignKeyAssociationViagem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewForeignKeyAssociationViagem));
        
        string IMigrationMetadata.Id
        {
            get { return "201910041353061_New-ForeignKey-Association-Viagem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
